### ISSUE TITLE
 Feature Roadmap: Upcoming Features and Echancements

### ISSUE THREAD

**Issue by vlf-stefan-drobic** [openagri-eu/irrigation-management#5]
This issue tracks all features and future releases. As features are implemented, they will be checked off and linked to their specific issues or pull requests.

#### Planned Features:

- [ ] **Specify interoperable ontology and integrate with OpenAgri Common Semantic Model**
  - Refactor input and output schemas to support updated OCSM models serialized in JSON-LD

- [ ] **Implement a versioning system**
  - Implement a versioning system alongside commits, that feature major and minor releases

- [ ] **Third-Party Integrations**
  - Integrate with GateKeeper as an API gateway service

Feel free to suggest additional features or comment on the proposed ones!

**Comment by mafragkopoulos** [comment]
In /api/v1/dataset/{dataset_id}/analysis response it would be useful to have dates array for precipitation_events and irrigation_events_detected as happens with the high_dose_irrigation_events, saturation_dates, stress_dates.

**Comment by prske** [comment]
Hi @mafragkopoulos 

Thank you for your suggestion. We will take a look into it and come back to you.

Regards.

**Comment by prske** [comment]
Hi @mafragkopoulos 

I have added new fields in ```/api/v1/dataset/{dataset_id}/analysis``` as you suggested. 
I will let you know once we merged into main and sync with this repository.

Regards.
